require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true

  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/**/*"
    - "config/environments/*"
    - "config/initializers/**/*"
    - "config/puma.rb"
    - "public/**/*"
    - "storage/**/*"

# メトリクスの制限を緩和
Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/models/match_info_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/requests/match_infos_spec.rb'
    - 'spec/system/match_infos_spec.rb'

# 1行の長さ制限
Layout/LineLength:
  Max: 120

# メソッドの改行ルール
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスにコメントを強制しない
Style/Documentation:
  Enabled: false

# コントローラ等のモジュールのネスト宣言を許可
Style/ClassAndModuleChildren:
  Enabled: false

# frozen_string_literal コメントを強制しない
Style/FrozenStringLiteralComment:
  Enabled: false

# ガード節の提案をしない
Style/GuardClause:
  Enabled: false

# 文字列のダブルクォート/シングルクォートの強制をしない
Style/StringLiterals:
  Enabled: false

# シンボル配列の%記法チェックを無効化
Style/SymbolArray:
  Enabled: false

# 文字列配列の%記法チェックを無効化
Style/WordArray:
  Enabled: false

# 変数名に数字を許可
Naming/VariableNumber:
  Enabled: false

# 代入と比較の誤りチェックを無効化
Lint/AssignmentInCondition:
  Enabled: false

# メソッド名の命名規則を厳しくしない
Naming/PredicateName:
  Enabled: false

# I18n未対応のチェックは警告に変更
Rails/I18nLocaleTexts:
  Severity: warn

# before_actionの際の未定義メソッドチェック
Rails/LexicallyScopedActionFilter:
  Enabled: false
