default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", ENV.fetch("USER")) %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>

development:
  <<: *default
  database: ttlog_development

test:
  <<: *default
  database: ttlog_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
